### ISSUE TITLE
[V1.3-V1.4] Prompt prefix for users

### ISSUE THREAD

**Issue by JYL123** [CS2103AUG2017-W11-B1/main#101]
e.g. Add n/ p/...

**Comment by lancehaoh** [comment]
Done

**Comment by JYL123** [comment]
Did you try to build project?

**Comment by lancehaoh** [comment]
I built this version on windows. I have not tried it on mac yet.

**Comment by lancehaoh** [comment]
Update: I just tested it on mac. It works.
