### ISSUE TITLE
Erratic behaviour in Autocorrect for search command

### ISSUE THREAD

**Issue by lancehaoh** [CS2103AUG2017-W11-B1/main#164]
Try the command "seh friends".

The autocorrect output is: **Your command: seh, is corrected to: sh**

Note that sh is not a valid command/alias. Yet the command executes successfully.

**Comment by JYL123** [comment]
sh is the alias for Search + Tag name, e.g. sh friends

**Comment by lancehaoh** [comment]
Oh. I didn't realise that. I have a suggestion though. Is it possible to hint the user about what the actual command name should be as well?

**Comment by JYL123** [comment]
Good suggestion
