### ISSUE TITLE
Invalid notation used in user guide

### ISSUE THREAD

**Issue by lancehaoh** [CS2103AUG2017-W11-B1/main#166]
There is a use of notation [TIP] in the user guide. Somehow, asciidoctor reports that this tag is "invalid for sidestyle block". I have included an excerpt of the paragraph at which the error occurs.

[TIP]
A person can have any number of tags (including 0).
A person can add the symbol '-' if a second phone number is not required for the contact.
Person names should only contain alphanumeric characters and spaces, and it should not be blank.
Person emails should be 2 alphanumeric/period strings separated by '@'.
Phone numbers can only contain numbers, and should be at least 3 digits long.
Tags names should be alphanumeric

Specifically, it occurs under the section "Editing a person".

I don't know whose part is this so I assigned everyone.

**Comment by JYL123** [comment]
This part is input by me last nite. I didn't have a time to change that yet. My plan is to change it before Tuesday.
