### ISSUE TITLE
code quality comments for JYL123

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W11-B1/main#200]
![image](https://user-images.githubusercontent.com/1023494/32641842-2f5f94cc-c60b-11e7-8dae-8fdfadbf6166.png)
- header comment doesn't follow the convention we specify

![image](https://user-images.githubusercontent.com/1023494/32641859-4ebab590-c60b-11e7-99c4-e27aad559e15.png)
- try to avoid magic numbers. may be better to use a constant here

@JYL123 FYA

**Comment by JYL123** [comment]
Fixed. Thanks for pointing out.
