### ISSUE TITLE
Bug in edittask: exception is thrown but no error is shown in feedback.

### ISSUE THREAD

**Issue by lancehaoh** [CS2103AUG2017-W11-B1/main#214]
Try this input:

edittask 3 d/cs2100 finals pr/priority 3 on date 02/08/2018

**Comment by JYL123** [comment]
![screen shot 2017-11-12 at 8 09 34 am](https://user-images.githubusercontent.com/24690889/32694664-dd618bd6-c780-11e7-84ed-c401eff7abdc.png)

**Comment by lancehaoh** [comment]
Please copy and paste the input that I suggested. The command that you used is not the same and will be handled differently.

**Comment by JYL123** [comment]
The format of the command you gave to me is not correct.

**Comment by lancehaoh** [comment]
We can't assume that users will always enter the correct format right? Our application must be able to handle incorrect instances gracefully.

**Comment by JYL123** [comment]
Please refer to the last issue you just created.

**Comment by lancehaoh** [comment]
Hmm. That is for a separate problem. This problem is related to a parse error in the application.

**Comment by JYL123** [comment]
Parsing string is not handled by me. The string is passed in AddressBookParser, which all arguments are processed in the same way. If this is an "error" then all task related commands share the same problem, formatting.  

And I don't think it is an error, but about how users are expected to use the application in the correct way, also it is logical that users cannot use the application in anyway they want. So what I can do is to document from a user's point of view as detailed as I can.

**Comment by lancehaoh** [comment]
Alright then.
