### ISSUE TITLE
Non-intuitiveness of edittask command

### ISSUE THREAD

**Issue by lancehaoh** [CS2103AUG2017-W11-B1/main#215]
Edittask is pretty non-intuitive to use. The user guide does not have a full command in its picture examples. Also, when extended autocomplete is used, the full format of the command is filled into the command box. This should have filled into the result panel instead so that the user does not have to remove all the placeholder text.

I also tried this command (which I think should be correct):

edittask 3 d/cs2100 finals pr/2 on date 02/08/2018

But the system reports that the date is incorrect. Why is this so? Based on the format stated in the user guide and the help text, this date should be valid.

P.s. Create 3 tasks before trying the above command.

**Edit**:

Ok. I realised that the format of the above command is invalid. The correct command should be:

edittask 3 d/cs2100 finals pr/2 on 02/08/2018

That probably shows how non-intuitive the help text is. I don't see a good example in the user guide either. Maybe you would want to fix this?

**Comment by JYL123** [comment]
Cool. Thanks. Fixing now.
